# Prefix definition
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX dbpedia: <http://dbpedia.org/ontology/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX nie: <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# Add file using curl
# curl -i -X POST -H "Content-Type: multipart/form-data" -F "file=@/blablabla/file.somewhere" http://localhost/files

# Query to create a new source
INSERT DATA {
  GRAPH <http://mu.semte.ch/application> {
    <http://example.com/sources/source_uuid> a ext:Source ;
                                                    mu:uuid "source_uuid" ;
                                                    ext:name "Lorem Ipsum" ;
                                                    ext:description "Copyleft (c) 2020 Copyright Holder All Rights Reserved. LOL";
                                                    dct:created "1970-01-01T00:00:00"^^xsd:dateTime .
  }
}


# Query to add SchemaAnalysisJob
# Remember to both change job_uuid in the beginning uri as well as in the uuid!
INSERT DATA {
  GRAPH <http://mu.semte.ch/application> {
    <http://example.com/schema-analysis-jobs/job_uuid> a ext:SchemaAnalysisJob ;
                                                    mu:uuid "job_uuid" ;
                                                    dct:created "1970-01-01T00:00:00"^^xsd:dateTime ;
                                                    ext:file <http://mu.semte.ch/services/file-service/files/file_uuid> .
    <http://example.com/sources/source_uuid> ext:jobs <http://example.com/schema-analysis-jobs/job_uuid> .

  }
}

# Delete job with given uuid
DELETE WHERE {
     GRAPH <http://mu.semte.ch/application> {
                <http://example.com/schema-analysis-jobs/job_uuid> ?p ?o .
     }
}


INSERT DATA {
  GRAPH <http://mu.semte.ch/application> {
    <http://example.com/files/> a nfo:FileDataObject ;
                                                    mu:uuid "" ;
                                                    nfo:fileName "" ;
                                                    nie:dataSource "";
                                                    dct:created "" ;
                                                    ext:contentType ;
                                                    dbpedia:fileExtension ;
                                                    nfo:fileSize ;
                                                    dct:format.
  }
}